apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
    - image: gcr.io/k8s-skaffold/skaffold-example
      docker:
        buildArgs:
          message: '{{ .MESSAGE | required }}'
deploy:
  kubectl:
    manifests:
      - k8s-*
    values:
      Name: '{{ .NAME | default "default-name" }}'
